create database PodeCast
go

use PodeCast
go

CREATE TABLE [dbo].[file_det] (
    [id]       INT           IDENTITY (1, 1) NOT NULL,
    [url]      VARCHAR (250) NOT NULL,
    [type]     VARCHAR (20)  NOT NULL,
    [duration] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);



CREATE TABLE [dbo].[episodes] (
    [id]           VARCHAR (500) NOT NULL,
    [title]        TEXT          NOT NULL,
    [members]      VARCHAR (100) NOT NULL,
    [published_at] TEXT          NOT NULL,
    [thumbnail]    TEXT          NOT NULL,
    [description]  TEXT          NOT NULL,
    [id_fileDet]   INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_file] FOREIGN KEY ([id_fileDet]) REFERENCES [dbo].[file_det] ([id])
);

truncate table file_det

INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/opensource.m4a', 'audio/x-m4a', 3981)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/funcional.m4a', 'audio/x-m4a', 4237)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/microservicos.m4a', 'audio/x-m4a', 5506)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/clean.m4a', 'audio/x-m4a', 5044)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/jose-valim.m4a', N'audio/x-m4a', 4396)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/design.m4a', 'audio/x-m4a', 2715)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/lider-desenvolvimento.m4a', 'audio/x-m4a', 2917)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/comunidade.m4a', 'audio/x-m4a', 2677)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/typescript.m4a', 'audio/x-m4a', 1772)
INSERT INTO [dbo].[file_det] ( [url], [type], [duration]) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/autenticacao.m4a', 'audio/x-m4a', 1463)

INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'a-importancia-da-contribuicao-em-open-source', N'Faladev #30 | A importância da contribuição em Open Source', N'Diego Fernandes, João Pedro, Diego Haz e Bruno Lemos', N'2021-01-22 16:35:40', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/opensource.jpg', N'<p>Nesse episódio do Faladev, Diego Fernandes se reúne com João Pedro Schmitz, Bruno Lemos e Diego Haz, para discutir sobre a importância da contribuição open source e quais desafios circulam na comunidade.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.</p>', 1)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'aplicacao-de-arquiteturas-mvc-e-clean-architecture-na-pratica', N'Faladev #27 | Aplicação de arquiteturas MVC e CA na prática', N'Diego Fernandes, Dani Leão, Otávio Lemos e Rodrigo Branas', N'2020-12-18 14:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/clean.jpg', N'<p>Diego Fernandes e Daniele Evangelista receberam Otávio Lemos e Rodrigo Branas para bater um papo sobre arquiteturas modernas de desenvolvimento, aplicadas na indústria da tecnologia.</p><p>Quais são os fundamentos, os princípios e a importância de debater arquiteturas neste ecossistema?</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.  Ficha técnica Hosts: Diego Fernandes e Daniele Leão Evangelista Convidados: Otávio Lemos  e Rodrigo Branas Roteiro: Felipe Buzzi, Beatriz Clasen e Thiago Marinho Edição: Thiago Santana Produção: Leonardo Minatti</p>', 4)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'barreiras-e-solucoes-propostas-por-micro-servicos', N'Faladev #28 | Por trás de barreiras e soluções propostas por micro-serviços', N'Diego Fernandes, Dani Leão, Wesley Williams e Lucas Santos', N'2021-01-08 13:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/microservicos.jpg', N'<p>Os desenvolvedores Wesley Willians e Lucas Santos foram convidados para este Faladev para ter uma conversa sobre o que são micro-serviços e quais são os desafios e as barreiras de sua aplicação.</p><p>Nessa edição, Diego Fernandes e Daniele Evangelista guiam a conversa levantando tópicos e questionamentos relevantes sobre o assunto.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.  #programação #rocketseat #programador #programador</p>', 3)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'como-virar-lider-desenvolvimento', N'Faladev #24 | Como virar líder de desenvolvimento?', N'Diego Fernandes, João Paulo e Cleiton Souza', N'2020-10-23 14:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/lider-desenvolvimento.jpg', N'<p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev. Nesse episódio, Diego Fernandes se reúne com Cleiton Souza e João Paulo de Magalhães para discutir sobre liderança, considerando aspectos profissionais, técnicos e até mesmo emocionais, o que envolve ser um líder de desenvolvimento? Afinal, o que é um líder de desenvolvimento?</p>', 7)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'comunidades-e-tecnologia', N'FalaDev #23 | O que comunidades têm a ver com tecnologia?', N'Diego Fernandes, Isabela Castilho e João Inácio', N'2020-10-16 13:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/comunidade.jpg', N'<p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev.</p><p>Nesse primeiro episódio da nova temporada, Diego Fernandes se reúne com Isabela Castilho e João Inácio Neto (Biro) para discutir sobre comunidades e o impacto que elas exercem na carreira de devs em busca do próximo nível. Afinal, O que é uma comunidade e o que tem a ver com tecnologia?</p>', 8)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'entrevista-jose-valim-criador-do-elixir', N'Faladev #26 | Especial: entrevista exclusiva com José Valim, criador da linguagem Elixir', N'Diego Fernandes e José Valim', N'2020-12-04 15:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/josevalim.jpg', N'<p>Nesta edição especial de final de temporada tivemos a oportunidade de ter uma conversa com José Valim, dev brasileiro que criou a linguagem de programação Elixir — utilizada internacionalmente em diversas tecnologias, incluindo Discord e Pinterest.</p><p>O assunto da semana girou em diversos processos envolvidos na criação de uma linguagem nova, que propõe ser uma alternativa eficiente no mercado da tecnologia.</p><p>Além de tudo isso, Valim pôde falar de muito código e sobre a sua jornada e experiência em criar uma comunidade ativa por trás do open source.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original da Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev.</p>', 5)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'estrategias-de-autenticacao-jwt-oauth', N'FalaDev #21 - Estratégias de autenticação, JWT, OAuth, qual usar?', N'Diego Fernandes, Higo Ribeiro e Guilherme Pellizzetti', N'2020-04-09 20:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/autenticacao.jpg', N'<p>Três programadores conversam sobre estratégia de autenticação.</p><p>Vamos discutir quais aspectos você deve considerar na hora de fazer a sua escolha.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso.</p>', 10)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'o-que-e-ui-ux', N'Faladev #25 | O que é UX/UI?', N'Diego Fernandes, Tiago Luchtenberg e Thainan Librelon', N'2020-10-30 14:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/design.jpg', N'<p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev.</p><p>Nesse episódio, Diego Fernandes se reúne com Thainan Librelon e Tiago Luchtenberg para discutir sobre: Desenvolvedor pode fazer o trabalho do UI/UX, qual impacto? Qual é o momento ideal pra ter pessoas especializadas em UX e UI? E afinal, o que é UI e o que é UX?</p>', 6)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'typescript-vale-a-pena', N'FalaDev #22 - TypeScript vale a pena? JavaScript perde sentido?', N'Diego Fernandes, Mayk Brito e João Pedro', N'2020-05-04 14:49:35', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/typescript.jpg', N'<p>Três programadores conversam sobre TypeScript.</p><p>Vamos discutir a usabilidade e as previsões da linguagem no cenário da programação.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso.</p>', 9)
INSERT INTO [dbo].[episodes] ([id], [title], [members], [published_at], [thumbnail], [description], [id_fileDet]) VALUES (N'uma-conversa-sobre-programacao-funcional-e-orientacao-a-objetos', N'Faladev #29 | Duas perspectivas diferentes na mesa: uma conversa sobre PF e OOP', N'Diego Fernandes, Dani Leão, Laura Beatris e Rafael Camarda', N'2021-01-15 13:00:00', N'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/funcional.jpg', N'<p>Diego e Dani receberam Laura Beatris e Rafael Camarda na mesa do Faladev para conversarem sobre programação funcional e programação orientada a objetos.</p><p>Análises de mercado, conceitos na prática e desafios na adoção de qualquer método de desenvolvimento. Tudo isso numa conversa dinâmica e relevante para nosso público.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.</p>\n', 2)
